services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - CHOKIDAR_USEPOLLING=true  # for Vite hot reload inside Docker

  api:
    build: ./api  
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver
      - django
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=HackathonDB;User Id=sa;Password=YourStrong!Passw0rd;
      - DJANGO_SERVICE_URL=http://django:8000

  django:
    build: ./micro-service
    ports:
      - "8000:8000"
    depends_on:
      - sqlserver
    environment:
      - DEBUG=True
      - DB_HOST=sqlserver
      - DB_NAME=HackathonDB
      - DB_USER=sa
      - DB_PASSWORD=YourStrong!Passw0rd

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U sa -P YourStrong!Passw0rd -Q 'SELECT 1'"]
      interval: 10s
      retries: 5

volumes:
  sqlserverdata:
